name: latex_to_pdf

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile latex document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          args: -interaction=nonstopmode -file-line-error -pdf
          continue_on_error: true
        continue-on-error: true
      - name: Check pdf files
        run: |
          file cv.pdf
      - name: Commit pdf files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat: updated cv.pdf"
          commit_options: "--no-verify"
          commit_user_name: "GitHub Action"
          commit_user_email: "action@github.com"
          branch: ${{ github.head_ref }}
          file_pattern: cv.pdf
          repository: .
